Repository robomechanics/quad-sdk, pull requests merged in 2020-09, with the labels that each got.

#6 Build server updated to test on x86 and arm
  .travis.yml
Labels: enhancement

#13 Update package template with it's own spin method
  package_template/include/package_template/package_template.h
  package_template/src/package_template.cpp
Labels: documentation

#26 Specify full path top top tier README
  Doxyfile
Labels: bug, documentation

#29 Update the footstep planner to include desired gait sequence, timing,…
  local_footstep_planner/src/local_footstep_planner.cpp
  spirit_utils/src/rviz_interface.cpp
Labels: enhancement

#31 Add FastTerrainMap to spirit_utils, and switch planners to use it
  global_body_planner/CMakeLists.txt
  global_body_planner/include/global_body_planner/functions.h
  global_body_planner/include/global_body_planner/global_body_planner.h
  global_body_planner/include/global_body_planner/planner_class.h
  global_body_planner/include/global_body_planner/rrt.h
  global_body_planner/include/global_body_planner/rrt_connect.h
  global_body_planner/include/global_body_planner/rrt_star_connect.h
  global_body_planner/package.xml
  global_body_planner/src/functions.cpp
  global_body_planner/src/global_body_planner.cpp
  global_body_planner/src/planner_class.cpp
  global_body_planner/src/rrt.cpp
  global_body_planner/src/rrt_connect.cpp
  global_body_planner/src/rrt_star_connect.cpp
  global_body_planner/src/simple_terrain_node.cpp
  local_footstep_planner/CMakeLists.txt
  local_footstep_planner/include/local_footstep_planner/local_footstep_planner.h
  local_footstep_planner/package.xml
  local_footstep_planner/src/local_footstep_planner.cpp
  spirit_utils/CMakeLists.txt
  spirit_utils/include/spirit_utils/fast_terrain_map.h
  spirit_utils/package.xml
  spirit_utils/src/fast_terrain_map.cpp
  spirit_utils/src/rviz_interface.cpp
  spirit_utils/test/test_fast_terrain_map.cpp
Labels: enhancement

#32 Add custom interp class
  ekf_estimator/include/ekf_estimator/ekf_estimator.h
  ekf_estimator/src/ekf_estimator.cpp
  spirit_utils/CMakeLists.txt
  spirit_utils/include/spirit_utils/class1.h
  spirit_utils/include/spirit_utils/fast_interpolator.h
  spirit_utils/src/class1.cpp
  spirit_utils/src/fast_interpolator.cpp
  spirit_utils/src/fast_interpolator_timecheck.cpp
  spirit_utils/test/test_fast_interpolator.cpp
  spirit_utils/test/test_main.cpp
  spirit_utils/test/test_rviz_interface.cpp
Labels: enhancement
