Repository robomechanics/quad-sdk, pull requests merged in 2021-03, with the labels that each got.

#120 Switch to individual config files, add /control namespace
  .travis.yml
  body_force_estimator/body_force_estimator.yaml
  config/project_params.yaml
  contact_detection/contact_detection.yaml
  ekf_estimator/ekf_estimator.yaml
  global_body_planner/global_body_planner.yaml
  inverse_dynamics/src/inverse_dynamics.cpp
  local_footstep_planner/local_footstep_planner.yaml
  mblink_converter/mblink_converter.yaml
  mblink_converter/src/mblink_converter.cpp
  mpc_controller/mpc_controller.yaml
  open_loop_controller/open_loop_controller.yaml
  open_loop_controller/src/open_loop_controller.cpp
  spirit_simulator/gazebo_scripts/include/controller_plugin.h
  spirit_simulator/gazebo_scripts/src/controller_plugin.cpp
  spirit_utils/config/grid_map_visualization.yaml
  spirit_utils/config/ground_truth_publisher.yaml
  spirit_utils/config/robot_proxy.yaml
  spirit_utils/config/rviz_interface.yaml
  spirit_utils/config/teleop_twist_keyboard.yaml
  spirit_utils/config/terrain_map_publisher.yaml
  spirit_utils/config/topics.yaml
  spirit_utils/config/trajectory_publisher.yaml
  spirit_utils/launch/control.launch
  spirit_utils/launch/estimation.launch
  spirit_utils/launch/load_params.launch
  spirit_utils/launch/logging.launch
  spirit_utils/launch/mapping.launch
  spirit_utils/launch/mocap.launch
  spirit_utils/launch/open_loop_robot_driver.launch
  spirit_utils/launch/planning.launch
  spirit_utils/launch/planning_tracking.launch
  spirit_utils/launch/remote_driver.launch
  spirit_utils/launch/robot_driver.launch
  spirit_utils/launch/robot_visual_config.launch
  spirit_utils/launch/spirit_gazebo.launch
  spirit_utils/launch/visualization.launch
  twist_body_planner/twist_body_planner.yaml
Labels: enhancement

#122 Add more foot transforms and clean up naming convention in kinematics
  spirit_utils/include/spirit_utils/kinematics.h
  spirit_utils/src/kinematics.cpp
  spirit_utils/test/test_kinematics.cpp
Labels: enhancement

#123 Add smooth transition in GBP from start state to heuristically planned states
  global_body_planner/include/global_body_planner/planning_utils.h
  global_body_planner/src/global_body_planner.cpp
  global_body_planner/src/planning_utils.cpp
  spirit_utils/config/terrain_map_publisher.yaml
  spirit_utils/include/spirit_utils/robot_proxy.h
  spirit_utils/src/robot_proxy.cpp
  spirit_utils/src/trajectory_publisher.cpp
Labels: bug

#124 Add execute_plan.launch, straighten up other launch files
  global_body_planner/src/planning_utils.cpp
  spirit_utils/launch/control.launch
  spirit_utils/launch/execute_plan.launch
  spirit_utils/launch/planning.launch
  spirit_utils/launch/remote_driver.launch
  spirit_utils/launch/robot_driver.launch
  spirit_utils/launch/spirit_gazebo.launch
  spirit_utils/src/trajectory_publisher.cpp
Labels: enhancement

#125 Add logging topics
  global_body_planner/src/global_body_planner.cpp
  local_footstep_planner/include/local_footstep_planner/local_footstep_planner.h
  local_footstep_planner/src/local_footstep_planner.cpp
  spirit_utils/include/spirit_utils/kinematics.h
  spirit_utils/include/spirit_utils/math_utils.h
  spirit_utils/launch/logging.launch
  spirit_utils/rviz/example_with_terrain.rviz
  spirit_utils/src/kinematics.cpp
  spirit_utils/src/math_utils.cpp
  spirit_utils/src/rviz_interface.cpp
  spirit_utils/src/trajectory_publisher.cpp
Labels: bug, enhancement

#126 Update planner params
  global_body_planner/global_body_planner.yaml
  global_body_planner/include/global_body_planner/global_body_planner.h
  global_body_planner/include/global_body_planner/graph_class.h
  global_body_planner/include/global_body_planner/planner_class.h
  global_body_planner/include/global_body_planner/planning_utils.h
  global_body_planner/include/global_body_planner/rrt.h
  global_body_planner/include/global_body_planner/rrt_connect.h
  global_body_planner/launch/diagnostics.launch
  global_body_planner/launch/example.launch
  global_body_planner/src/global_body_planner.cpp
  global_body_planner/src/graph_class.cpp
  global_body_planner/src/planner.cpp
  global_body_planner/src/planner_class.cpp
  global_body_planner/src/planning_utils.cpp
  global_body_planner/src/rrt.cpp
  global_body_planner/src/rrt_connect.cpp
  local_footstep_planner/src/local_footstep_planner.cpp
  spirit_utils/config/terrain_map_publisher.yaml
  spirit_utils/config/trajectory_publisher.yaml
  spirit_utils/data/step/nx_data.csv
  spirit_utils/data/step/nx_data_filt.csv
  spirit_utils/data/step/ny_data.csv
  spirit_utils/data/step/ny_data_filt.csv
  spirit_utils/data/step/nz_data.csv
  spirit_utils/data/step/nz_data_filt.csv
  spirit_utils/data/step/x_data.csv
  spirit_utils/data/step/y_data.csv
  spirit_utils/data/step/z_data.csv
  spirit_utils/data/step/z_data_filt.csv
  spirit_utils/include/spirit_utils/fast_terrain_map.h
  spirit_utils/include/spirit_utils/terrain_map_publisher.h
  spirit_utils/include/spirit_utils/trajectory_publisher.h
  spirit_utils/launch/remote_driver.launch
  spirit_utils/launch/visualization.launch
  spirit_utils/src/fast_terrain_map.cpp
  spirit_utils/src/terrain_map_publisher.cpp
  spirit_utils/src/trajectory_publisher.cpp
Labels: bug

#129 Add GBP parameter to allow/prohibit replanning
  global_body_planner/global_body_planner.yaml
  global_body_planner/include/global_body_planner/global_body_planner.h
  global_body_planner/src/global_body_planner.cpp
Labels: enhancement

#130 Add sparse convex QP-based MPC
  inverse_dynamics/src/inverse_dynamics.cpp
  mpc_controller/include/mpc_controller/quadruped_mpc.h
  mpc_controller/mpc_controller.yaml
  mpc_controller/src/mpc_controller.cpp
  mpc_controller/src/quadruped_mpc.cpp
  mpc_controller/test/test_quadruped_mpc.cpp
  open_loop_controller/src/open_loop_controller.cpp
  spirit_simulator/gazebo_scripts/launch/spirit_gazebo.launch
  spirit_utils/launch/planning.launch
  spirit_utils/launch/remote_driver.launch
  spirit_utils/src/foot_jacobians.cpp
Labels: enhancement

#131 Updated SDF to add independent toe link
  spirit_simulator/gazebo_scripts/src/estimator_plugin.cpp
  spirit_simulator/spirit_description/sdf_mesh/spirit (old).sdf
  spirit_simulator/spirit_description/sdf_mesh/spirit.sdf
  spirit_simulator/spirit_description/sdf_mesh/spirit_original.sdf
Labels: enhancement
